name: 'Security Tools Action'
description: 'Run various security tools'
inputs:
  tool:
    description: 'Security tool to run'
    required: true
  g_token:
    description: 'GitHub Personal Access Token'
    required: true
  g_username:
    description: 'GitHub Username'
    required: true
  semgrep_token:
    description: 'SemGrep App Token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install Logger
      run: pip install loguru
      shell: bash

    - name: Install Bandit
      if: inputs.tool == 'web'
      run: pip install bandit safety
      shell: bash

    - name: Install Checkov
      if: inputs.tool == 'iac'
      run: pip install checkov
      shell: bash

    - name: Run Security Tools
      run: python ${{ github.action_path }}/main.py
      shell: bash
      env:
        TOOL: ${{ inputs.tool }}
        G_TOKEN: ${{ inputs.g_token }}
        G_USERNAME: ${{ inputs.g_username }}
    
    - name: Run Security Tools Depcheck
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'test'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --failOnCVSS 7
          --enableRetired
