name: 'Security Tools Action'
description: 'Run various security tools'
inputs:
  tool:
    description: 'Security tool to run'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install Logger
      run: pip install loguru
      shell: bash

    - name: Install Bandit
      if: inputs.tool == 'bandit'
      run: pip install bandit
      shell: bash

    - name: Install Checkov
      if: inputs.tool == 'checkov'
      run: pip install checkov
      shell: bash

    - name: Run Security Tool
      run: python ${{ github.action_path }}/${{ inputs.tools }}/main.py
      shell: bash
      env:
        TOOL: ${{ inputs.tools }}
