name: 'Security Tools Action'
description: 'Run various security tools'
inputs:
  tool:
    description: 'Security tool to run'
    required: true
  g_token:
    description: 'GitHub Personal Access Token'
    required: true
  g_username:
    description: 'GitHub Username'
    required: true
  semgrep_token:
    description: 'SemGrep App Token'
    required: true
  file_name:
    description: 'File name for the MobSF to scan'
    required: false
  output_file_name:
    description: 'Output file name for the MobSF report'
    required: false
  scan_type:
    description: 'Type of scan for MobSF to perform (apk, ipa, appx)'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Run TruffleHog
      if: ${{ inputs.context == 'web' || inputs.context == 'mobile' }}
      run: |
        docker run --rm -i -v "${{ github.workspace }}:/pwd" trufflesecurity/trufflehog:latest git https://${{ inputs.g_username }}:${{ inputs.g_token }}@github.com/${{ github.repository_owner }}/${{ github.repository }}.git --json > trufflehog-results.json
        cat trufflehog-results.json
      shell: bash
      env:
        G_TOKEN: ${{ inputs.g_token }}
        G_USERNAME: ${{ inputs.g_username }}
    
    - name: Run Dependency-Check
      if: ${{ inputs.context == 'web' || inputs.context == 'mobile' }}
      run: |
        docker run --rm -v "${{ github.workspace }}:/src" owasp/dependency-check --project "Dependency Check" --scan "/src" --out "/src/reports" --format "HTML"
      shell: bash
      env:
        WORKSPACE: ${{ github.workspace }}
    
    - name: Run Checkov
      if: ${{ inputs.tool == 'iac' }}
      run: |
        docker run --tty --volume ${{ github.workspace }}:/code bridgecrew/checkov:latest -d /code
      shell: bash
    
    - name: Run MobSF
      if: ${{ inputs.tool == 'mobile' }}
      env:
        INPUT_FILE_NAME: ${{ inputs.file_name }}
        OUTPUT_FILE_NAME: ${{ inputs.output_file_name }}
        SCAN_TYPE: ${{ inputs.scan_type }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        docker build -t mobsfscan -f .github/workflows/mobsf/Dockerfile .github/workflows/mobsf/
        docker run --rm -v "${{ github.workspace }}:/github/workspace" --network host mobsfscan
      shell: bash

    - name: Run Semgrep
      if: ${{ inputs.context == 'web' || inputs.context == 'mobile' }}
      env:
        SEMGREP_APP_TOKEN: ${{ inputs.semgrep_token }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        docker run -e SEMGREP_APP_TOKEN=${{ inputs.semgrep_token }} --rm -v "${GITHUB_WORKSPACE}:/src" returntocorp/semgrep semgrep ci
      shell: bash